export const WISH_LOAD = 'WISH_LOAD';
export const WISH_LOAD_SUCCESS = 'WISH_LOAD_SUCCESS';
export const WISH_LOAD_FAIL = 'WISH_LOAD_FAIL';
export const WISH_CREATE = 'WISH_CREATE';
export const WISH_CREATE_SUCCESS = 'WISH_CREATE_SUCCESS';
export const WISH_CREATE_FAIL = 'WISH_CREATE_FAIL';
export const WISH_DESTROY = 'WISH_DESTROY';
export const WISH_DESTROY_SUCCESS = 'WISH_DESTROY_SUCCESS';
export const WISH_DESTROY_FAIL = 'WISH_DESTROY_FAIL';

export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';
export const AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';

